---
name: Build container images

on:
  push:
    branches: [ $default-branch, imagefactory ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  Run-ImageFactory-Builds:
    strategy:
      matrix: 
        architecture:
          - x64
          - ARM64
        variant:
          - Base
          - Minimal
          - UBI
    runs-on: 
      - self-hosted
      - ${{ matrix.architecture }}
    steps:
      - name: Checkout sig-cloud-instance-images
        uses: actions/checkout@v2

      - name: Build images
        run: make VARIANT=${{ matrix.variant }}

      - name: Get image name
        run: echo "ARTIFACT_NAME=$(make publish VARIANT=${{ matrix.variant }})" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/
          if-no-files-found: error
